# Generated by Django 4.2.11 on 2026-05-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('n_ports', models.IntegerField(default=0)),
                ('n_flows', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('threat_type', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('mitigated', 'Mitigated'), ('false_positive', 'False Positive')], default='detected', max_length=16)),
                ('mitigation_rule', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port_no', models.IntegerField(null=True)),
                ('is_iot', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='dashboard.switch')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('switch_connected', 'Switch Connected'), ('switch_disconnected', 'Switch Disconnected'), ('flow_installed', 'Flow Installed'), ('flow_removed', 'Flow Removed'), ('host_detected', 'Host Detected'), ('link_up', 'Link Up'), ('link_down', 'Link Down'), ('threat_detected', 'Threat Detected'), ('mitigation_applied', 'Mitigation Applied'), ('error', 'Error')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_e_timesta_2fdad8_idx')],
            },
        ),
    ]
